# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

defaults: &defaults
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ci
    environment:
      JVM_OPTS: -Xmx1024m
      TERM: dumb

orbs:
  owasp: entur/owasp@0.0.4

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testCi
      - store_test_results:
          path: build/reports

workflows:
  version: 2
  test:
    jobs:
      - owasp/gradle_owasp_dependency_check:
          report_path: build/reports/CVEs
      - test
