# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

defaults: &defaults
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx1024m
      TERM: dumb

orbs:
  owasp: entur/owasp@0.0.4

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  test:
    <<: *defaults
    steps:
      - run: ./gradlew test
      # Get code coverage
      - run: ./gradlew jacocoTestReport
      - store_artifacts:
          path:  build/reports/jacoco


workflows:
  version: 2
  test:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - owasp/gradle_owasp_dependency_check:
          requires:
            - dependencies
          executor: java_8
          context: global
